// Conteúdo introdutório para crianças e famílias. As referências ajudam na
// revisão editorial; o texto deve passar por revisão bíblica, catequética e de
// linguagem inclusiva antes de uma publicação definitiva.
export const MIRACLE_ITEMS = [
  {
    id: 'water-into-wine',
    image: require('../../../assets/miracles/01-water-into-wine.png'),
    showEmojiBadge: false,
    name: 'Água Transformada em Vinho',
    shortDescription: 'Jesus leva alegria e abundância à festa de Caná.',
    emoji: '🏺',
    visual: { glyph: '🏺', backgroundColor: '#E7C9BB' },
    story: [
      'Jesus, Maria e os discípulos participavam de uma festa de casamento em Caná.',
      'Quando o vinho acabou, Jesus pediu que enchessem de água seis grandes jarros.',
      'A água foi transformada em vinho, e os discípulos começaram a crer nele.',
    ],
    fact: 'O Evangelho de João apresenta Caná como o primeiro sinal realizado por Jesus.',
    metadata: {
      miracleType: 'Providência',
      gospel: 'João',
      teaching: 'Confiança',
      references: ['João 2,1–11'],
    },
  },
  {
    id: 'miraculous-catch',
    image: require('../../../assets/miracles/02-miraculous-catch.png'),
    showEmojiBadge: false,
    name: 'A Pesca Milagrosa',
    shortDescription: 'Uma rede vazia volta cheia de peixes.',
    emoji: '🐟',
    visual: { glyph: '🐟🐟', backgroundColor: '#C9E5EA' },
    story: [
      'Depois de uma noite sem pescar nada, Simão e seus companheiros encontraram Jesus na margem.',
      'Confiando na palavra de Jesus, lançaram novamente as redes e recolheram muitos peixes.',
      'Jesus então os convidou a segui-lo e participar de sua missão.',
    ],
    fact: 'A pesca abundante acompanha o chamado dos primeiros discípulos no Evangelho de Lucas.',
    metadata: {
      miracleType: 'Providência',
      gospel: 'Lucas',
      teaching: 'Confiança',
      references: ['Lucas 5,1–11'],
    },
  },
  {
    id: 'calming-storm',
    image: require('../../../assets/miracles/03-calming-storm.png'),
    showEmojiBadge: false,
    name: 'Jesus Acalma a Tempestade',
    shortDescription: 'Jesus traz paz em meio ao vento e às ondas.',
    emoji: '⛵',
    visual: { glyph: '⛵', backgroundColor: '#BDDCE8' },
    story: [
      'Jesus atravessava o lago com os discípulos quando uma forte tempestade começou.',
      'Eles ficaram com medo e pediram ajuda. Jesus acalmou o vento e o mar.',
      'O relato convida os discípulos a confiar nele mesmo nos momentos difíceis.',
    ],
    fact: 'O sinal revela a autoridade de Jesus e sua presença junto dos discípulos amedrontados.',
    metadata: {
      miracleType: 'Natureza',
      gospel: 'Marcos',
      teaching: 'Confiança',
      references: ['Marcos 4,35–41'],
    },
  },
  {
    id: 'multiplication-loaves',
    image: require('../../../assets/miracles/04-multiplication-loaves.png'),
    showEmojiBadge: false,
    name: 'A Multiplicação dos Pães',
    shortDescription: 'Pães e peixes alimentam uma grande multidão.',
    emoji: '🥖',
    visual: { glyph: '🥖🐟', backgroundColor: '#EAD5AC' },
    story: [
      'Uma grande multidão seguia Jesus e precisava de alimento.',
      'Um menino ofereceu cinco pães e dois peixes, e Jesus deu graças e os distribuiu.',
      'Todos comeram, e ainda foram recolhidos doze cestos com o que sobrou.',
    ],
    fact: 'O sinal revela a abundância do cuidado de Jesus e inspira a partilha.',
    metadata: {
      miracleType: 'Providência',
      gospel: 'João',
      teaching: 'Partilha',
      references: ['João 6,1–15'],
    },
  },
  {
    id: 'walking-on-water',
    image: require('../../../assets/miracles/05-walking-on-water.png'),
    showEmojiBadge: false,
    name: 'Jesus Caminha sobre as Águas',
    shortDescription: 'Jesus se aproxima dos discípulos sobre o lago.',
    emoji: '🌊',
    visual: { glyph: '🌊✨', backgroundColor: '#C6DFEA' },
    story: [
      'Durante a noite, os discípulos estavam no barco enfrentando vento forte.',
      'Jesus foi até eles caminhando sobre a água e disse que não tivessem medo.',
      'Pedro tentou ir ao encontro dele e aprendeu a confiar em sua ajuda.',
    ],
    fact: 'Ao entrar no barco, Jesus foi reconhecido pelos discípulos como Filho de Deus.',
    metadata: {
      miracleType: 'Natureza',
      gospel: 'Mateus',
      teaching: 'Fé',
      references: ['Mateus 14,22–33'],
    },
  },
  {
    id: 'paralytic',
    image: require('../../../assets/miracles/06-paralytic.png'),
    showEmojiBadge: false,
    name: 'O Homem Levado pelos Amigos',
    shortDescription: 'Amigos abrem o teto para aproximar um homem de Jesus.',
    emoji: '🏠',
    visual: { glyph: '🏠', backgroundColor: '#DCCFBF' },
    story: [
      'Quatro amigos queriam levar até Jesus um homem que não conseguia caminhar.',
      'Como a casa estava cheia, abriram uma passagem no teto e desceram a maca.',
      'Jesus acolheu a confiança daquele grupo, perdoou o homem e o curou.',
    ],
    fact: 'O cuidado dos amigos faz parte marcante deste encontro com Jesus.',
    metadata: {
      miracleType: 'Cura',
      gospel: 'Marcos',
      teaching: 'Fé',
      references: ['Marcos 2,1–12'],
    },
  },
  {
    id: 'man-born-blind',
    image: require('../../../assets/miracles/07-man-born-blind.png'),
    showEmojiBadge: false,
    name: 'O Homem que Passou a Enxergar',
    shortDescription: 'Jesus encontra um homem que não enxergava desde o nascimento.',
    emoji: '👁️',
    visual: { glyph: '👁', backgroundColor: '#F2E2B6' },
    story: [
      'Os discípulos encontraram um homem que não enxergava desde o nascimento.',
      'Jesus rejeitou a ideia de que aquela condição fosse castigo por algum pecado.',
      'Depois do encontro e da cura, o homem passou a reconhecer cada vez melhor quem era Jesus.',
    ],
    fact: 'O relato também fala de uma visão interior que cresce no diálogo e na fé.',
    metadata: {
      miracleType: 'Cura',
      gospel: 'João',
      teaching: 'Vida nova',
      references: ['João 9,1–41'],
    },
  },
  {
    id: 'leper-cleansed',
    image: require('../../../assets/miracles/08-leper-cleansed.png'),
    showEmojiBadge: false,
    name: 'Jesus Acolhe um Homem com Lepra',
    shortDescription: 'Jesus se aproxima, acolhe e cura com compaixão.',
    emoji: '🤲',
    visual: { glyph: '🤲', backgroundColor: '#D9E5D2' },
    story: [
      'Um homem com lepra aproximou-se de Jesus e pediu para ser purificado.',
      'Jesus estendeu a mão, tocou nele e o curou.',
      'O gesto revela compaixão e proximidade com quem vivia afastado da comunidade.',
    ],
    fact: 'Além da cura, o encontro abria um caminho para a reintegração daquela pessoa.',
    metadata: {
      miracleType: 'Cura',
      gospel: 'Mateus',
      teaching: 'Compaixão',
      references: ['Mateus 8,1–4'],
    },
  },
  {
    id: 'centurion-servant',
    image: require('../../../assets/miracles/09-centurion-servant.png'),
    showEmojiBadge: false,
    name: 'O Servo do Centurião',
    shortDescription: 'Um centurião confia na palavra de Jesus.',
    emoji: '🛡️',
    visual: { glyph: '🛡', backgroundColor: '#D6DCE6' },
    story: [
      'Um centurião procurou Jesus porque seu servo estava sofrendo muito.',
      'Ele confiava que uma palavra de Jesus seria suficiente, mesmo à distância.',
      'Jesus reconheceu aquela fé, e o servo foi curado.',
    ],
    fact: 'As palavras do centurião inspiram uma oração rezada antes da Comunhão na Missa.',
    metadata: {
      miracleType: 'Cura',
      gospel: 'Mateus',
      teaching: 'Fé',
      references: ['Mateus 8,5–13'],
    },
  },
  {
    id: 'woman-healed',
    image: require('../../../assets/miracles/10-woman-healed.png'),
    showEmojiBadge: false,
    name: 'A Mulher que Tocou o Manto',
    shortDescription: 'Uma mulher se aproxima de Jesus com confiança.',
    emoji: '🧵',
    visual: { glyph: '🧵', backgroundColor: '#E2D2E8' },
    story: [
      'Uma mulher que sofria havia muitos anos aproximou-se de Jesus no meio da multidão.',
      'Ela tocou seu manto com confiança e percebeu que estava curada.',
      'Jesus parou para vê-la, ouvi-la e chamá-la de filha.',
    ],
    fact: 'Jesus não deixou que a mulher permanecesse anônima: falou com ela com dignidade e paz.',
    metadata: {
      miracleType: 'Cura',
      gospel: 'Marcos',
      teaching: 'Fé',
      references: ['Marcos 5,25–34'],
    },
  },
  {
    id: 'jairus-daughter',
    image: require('../../../assets/miracles/11-jairus-daughter.png'),
    showEmojiBadge: false,
    name: 'A Filha de Jairo Volta à Vida',
    shortDescription: 'Jesus devolve uma menina ao convívio de sua família.',
    emoji: '🤝',
    visual: { glyph: '🤝', backgroundColor: '#F0D1D6' },
    story: [
      'Jairo pediu ajuda a Jesus porque sua filha estava muito doente.',
      'Quando chegaram à casa, Jesus tomou a menina pela mão e a chamou para levantar.',
      'Ela voltou à vida, e Jesus pediu que lhe dessem algo para comer.',
    ],
    fact: 'O gesto de dar alimento mostra o cuidado simples e concreto de Jesus com a menina.',
    metadata: {
      miracleType: 'Vida restaurada',
      gospel: 'Marcos',
      teaching: 'Vida nova',
      references: ['Marcos 5,21–24', 'Marcos 5,35–43'],
    },
  },
  {
    id: 'lazarus',
    image: require('../../../assets/miracles/12-lazarus.png'),
    showEmojiBadge: false,
    name: 'Lázaro Volta à Vida',
    shortDescription: 'Jesus chama seu amigo Lázaro para fora do túmulo.',
    emoji: '🌅',
    visual: { glyph: '🌅', backgroundColor: '#E7DEC3' },
    story: [
      'Marta e Maria estavam de luto pela morte de seu irmão Lázaro, amigo de Jesus.',
      'Jesus chorou com elas e foi até o túmulo.',
      'Então chamou Lázaro para fora, e a família recebeu de volta aquele que amava.',
    ],
    fact: 'Antes do sinal, Jesus se apresenta a Marta como a ressurreição e a vida.',
    metadata: {
      miracleType: 'Vida restaurada',
      gospel: 'João',
      teaching: 'Vida nova',
      references: ['João 11,1–44'],
    },
  },
  {
    id: 'deaf-man',
    image: require('../../../assets/miracles/13-deaf-man.png'),
    showEmojiBadge: false,
    name: 'O Homem que Passou a Ouvir',
    shortDescription: 'Jesus dedica atenção pessoal a um homem que não ouvia bem.',
    emoji: '👂',
    visual: { glyph: '👂', backgroundColor: '#D7E4DA' },
    story: [
      'Algumas pessoas levaram até Jesus um homem que não ouvia bem e tinha dificuldade para falar.',
      'Jesus o conduziu para um lugar reservado e cuidou dele com atenção.',
      'O homem passou a ouvir e a falar com clareza.',
    ],
    fact: 'A palavra “Efatá”, usada por Jesus neste relato, significa “Abre-te”.',
    metadata: {
      miracleType: 'Cura',
      gospel: 'Marcos',
      teaching: 'Compaixão',
      references: ['Marcos 7,31–37'],
    },
  },
  {
    id: 'ten-lepers',
    image: require('../../../assets/miracles/14-ten-lepers.png'),
    showEmojiBadge: false,
    name: 'Os Dez Homens Curados',
    shortDescription: 'Dez homens são curados, e um retorna agradecido.',
    emoji: '🙌',
    visual: { glyph: '🙌', backgroundColor: '#DCE6C9' },
    story: [
      'Dez homens com lepra pediram que Jesus tivesse compaixão deles.',
      'Enquanto seguiam a orientação recebida, perceberam que estavam curados.',
      'Um deles voltou, agradeceu e reconheceu o bem que havia recebido.',
    ],
    fact: 'O homem que retornou para agradecer era samaritano, alguém visto como estrangeiro pelo grupo.',
    metadata: {
      miracleType: 'Cura',
      gospel: 'Lucas',
      teaching: 'Gratidão',
      references: ['Lucas 17,11–19'],
    },
  },
  {
    id: 'widow-nain-son',
    image: require('../../../assets/miracles/15-widow-nain-son.png'),
    showEmojiBadge: false,
    name: 'O Filho da Viúva de Naim',
    shortDescription: 'Jesus se compadece de uma mãe e restaura sua alegria.',
    emoji: '🫂',
    visual: { glyph: '🫂', backgroundColor: '#EBD0C1' },
    story: [
      'Ao chegar à cidade de Naim, Jesus encontrou uma mãe viúva que havia perdido seu único filho.',
      'Cheio de compaixão, aproximou-se e chamou o jovem para se levantar.',
      'O filho voltou à vida e foi entregue à sua mãe.',
    ],
    fact: 'O relato destaca a compaixão de Jesus antes mesmo de alguém lhe fazer um pedido.',
    metadata: {
      miracleType: 'Vida restaurada',
      gospel: 'Lucas',
      teaching: 'Compaixão',
      references: ['Lucas 7,11–17'],
    },
  },
  {
    id: 'peters-mother-in-law',
    image: require('../../../assets/miracles/16-peters-mother-in-law.png'),
    showEmojiBadge: false,
    name: 'A Sogra de Pedro é Curada',
    shortDescription: 'Jesus toma sua mão, e ela se levanta restaurada.',
    emoji: '🤲',
    visual: { glyph: '🤲', backgroundColor: '#E7D5C8' },
    story: [
      'Na casa de Pedro, Jesus encontrou a sogra dele de cama e com febre.',
      'Ele tocou sua mão, e a febre desapareceu.',
      'Restabelecida, ela se levantou e voltou a acolher as pessoas da casa.',
    ],
    fact: 'Este breve relato acontece logo depois de outras ações de Jesus em Cafarnaum.',
    metadata: {
      miracleType: 'Cura',
      gospel: 'Mateus',
      teaching: 'Compaixão',
      references: ['Mateus 8,14–15'],
    },
  },
  {
    id: 'withered-hand',
    image: require('../../../assets/miracles/17-withered-hand.png'),
    showEmojiBadge: false,
    name: 'O Homem da Mão Paralisada',
    shortDescription: 'Jesus coloca o bem da pessoa no centro do sábado.',
    emoji: '✋',
    visual: { glyph: '✋', backgroundColor: '#D8E0D5' },
    story: [
      'Em uma sinagoga, estava um homem com uma das mãos paralisada.',
      'Jesus perguntou se no sábado era permitido fazer o bem e salvar uma vida.',
      'Então pediu que o homem estendesse a mão, e ela foi restaurada.',
    ],
    fact: 'O encontro ensina que a lei de Deus nunca deve ser usada para impedir o bem.',
    metadata: {
      miracleType: 'Cura',
      gospel: 'Marcos',
      teaching: 'Compaixão',
      references: ['Marcos 3,1–6'],
    },
  },
  {
    id: 'coin-in-fish',
    image: require('../../../assets/miracles/18-coin-in-fish.png'),
    showEmojiBadge: false,
    name: 'A Moeda Encontrada no Peixe',
    shortDescription: 'Uma moeda inesperada aparece durante uma pescaria.',
    emoji: '🐟',
    visual: { glyph: '🐟🪙', backgroundColor: '#C8E3DF' },
    story: [
      'Algumas pessoas perguntaram a Pedro sobre o imposto destinado ao Templo.',
      'Jesus o enviou para pescar e disse que encontraria uma moeda no primeiro peixe.',
      'A moeda seria suficiente para cumprir a obrigação de ambos.',
    ],
    fact: 'O episódio une uma cena cotidiana de pesca a um ensinamento sobre liberdade e responsabilidade.',
    metadata: {
      miracleType: 'Providência',
      gospel: 'Mateus',
      teaching: 'Responsabilidade',
      references: ['Mateus 17,24–27'],
    },
  },
];
