// Conteúdo introdutório para crianças e famílias. As referências ajudam na
// revisão editorial; o texto deve passar por revisão bíblica e catequética
// antes de uma publicação definitiva.
export const BIBLICAL_PLACE_ITEMS = [
  {
    id: 'jerusalem',
    name: 'Jerusalém',
    shortDescription: 'A cidade da Páscoa de Jesus e do nascimento da Igreja.',
    emoji: '🏛️',
    visual: { glyph: '🏛', backgroundColor: '#F1D9BD' },
    story: [
      'Jesus foi muitas vezes a Jerusalém e ali viveu os acontecimentos de sua Páscoa.',
      'Depois da Ressurreição, os discípulos receberam o Espírito Santo e começaram a anunciar o Evangelho.',
    ],
    fact: 'Jerusalém aparece muitas vezes tanto no Antigo quanto no Novo Testamento.',
    metadata: {
      period: 'Antigo e Novo Testamento',
      placeType: 'Cidade',
      region: 'Judeia',
      journey: 'Antigo e Novo Testamento',
      references: ['Lucas 24', 'Atos 2'],
    },
  },
  {
    id: 'bethlehem',
    name: 'Belém',
    shortDescription: 'A pequena cidade onde Jesus nasceu.',
    emoji: '⭐',
    visual: { glyph: '⭐', backgroundColor: '#F8E8B5' },
    story: [
      'Maria e José foram a Belém antes do nascimento de Jesus.',
      'Ali, Jesus nasceu e foi colocado numa manjedoura.',
    ],
    fact: 'Belém também está ligada à história de Rute e à família do rei Davi.',
    metadata: {
      period: 'Antigo e Novo Testamento',
      placeType: 'Cidade',
      region: 'Judeia',
      journey: 'Antigo e Novo Testamento',
      references: ['Rute 1–4', 'Miqueias 5,1', 'Lucas 2,1–20'],
    },
  },
  {
    id: 'nazareth',
    name: 'Nazaré',
    shortDescription: 'A cidade onde Jesus cresceu com Maria e José.',
    emoji: '🏠',
    visual: { glyph: '🏠', backgroundColor: '#DDE9CF' },
    story: [
      'Em Nazaré, o anjo Gabriel anunciou a Maria que ela seria a mãe de Jesus.',
      'Jesus viveu ali com Maria e José durante muitos anos.',
    ],
    fact: 'Por ter vivido em Nazaré, Jesus também ficou conhecido como Jesus de Nazaré.',
    metadata: {
      period: 'Novo Testamento',
      placeType: 'Cidade',
      region: 'Galileia',
      journey: 'Vida de Jesus',
      references: ['Lucas 1,26–38', 'Lucas 2,39–52'],
    },
  },
  {
    id: 'capernaum',
    name: 'Cafarnaum',
    shortDescription: 'Uma cidade importante na missão de Jesus na Galileia.',
    emoji: '🏘️',
    visual: { glyph: '🏘', backgroundColor: '#CFE5E4' },
    story: [
      'Jesus ensinou na sinagoga de Cafarnaum e realizou curas na cidade.',
      'Dali, percorreu outros lugares da Galileia anunciando o Reino de Deus.',
    ],
    fact: 'Cafarnaum ficava próxima ao Mar da Galileia e à região dos pescadores.',
    metadata: {
      period: 'Novo Testamento',
      placeType: 'Cidade',
      region: 'Galileia',
      journey: 'Vida de Jesus',
      references: ['Marcos 1,21–34', 'Mateus 4,13'],
    },
  },
  {
    id: 'cana',
    name: 'Caná',
    shortDescription: 'O lugar das bodas e do primeiro sinal de Jesus.',
    emoji: '🏺',
    visual: { glyph: '🏺', backgroundColor: '#E6D6C9' },
    story: [
      'Jesus, Maria e os discípulos participaram de uma festa de casamento em Caná.',
      'Quando o vinho acabou, Jesus transformou água em vinho e manifestou sua glória.',
    ],
    fact: 'O Evangelho de João chama esse acontecimento de primeiro sinal realizado por Jesus.',
    metadata: {
      period: 'Novo Testamento',
      placeType: 'Cidade',
      region: 'Galileia',
      journey: 'Vida de Jesus',
      references: ['João 2,1–11'],
    },
  },
  {
    id: 'bethany',
    name: 'Betânia',
    shortDescription: 'A aldeia dos amigos Marta, Maria e Lázaro.',
    emoji: '🌿',
    visual: { glyph: '🌿', backgroundColor: '#D7E5C7' },
    story: [
      'Em Betânia viviam Marta, Maria e Lázaro, amigos de Jesus.',
      'Jesus visitou a família e chamou Lázaro para fora do túmulo.',
    ],
    fact: 'Betânia ficava perto de Jerusalém, junto ao caminho do Monte das Oliveiras.',
    metadata: {
      period: 'Novo Testamento',
      placeType: 'Cidade',
      region: 'Judeia',
      journey: 'Vida de Jesus',
      references: ['Lucas 10,38–42', 'João 11,1–44'],
    },
  },
  {
    id: 'jericho',
    name: 'Jericó',
    shortDescription: 'A cidade onde Zaqueu subiu numa árvore para ver Jesus.',
    emoji: '🌳',
    visual: { glyph: '🌳', backgroundColor: '#D9E4BD' },
    story: [
      'Ao passar por Jericó, Jesus encontrou Zaqueu, que havia subido num sicômoro.',
      'Jesus foi à casa dele, e esse encontro transformou sua maneira de viver.',
    ],
    fact: 'Jericó também é conhecida no Antigo Testamento pela história de suas muralhas.',
    metadata: {
      period: 'Antigo e Novo Testamento',
      placeType: 'Cidade',
      region: 'Judeia',
      journey: 'Vida de Jesus',
      references: ['Josué 6', 'Lucas 19,1–10'],
    },
  },
  {
    id: 'emmaus',
    name: 'Emaús',
    shortDescription: 'O destino dos discípulos que caminharam com Jesus ressuscitado.',
    emoji: '🥖',
    visual: { glyph: '🥖', backgroundColor: '#E9D4B3' },
    story: [
      'Dois discípulos caminhavam para Emaús quando Jesus ressuscitado se aproximou.',
      'Eles o reconheceram mais tarde, quando Jesus partiu o pão.',
    ],
    fact: 'O Evangelho conta a caminhada, mas existem diferentes propostas para localizar Emaús atualmente.',
    metadata: {
      period: 'Novo Testamento',
      placeType: 'Cidade',
      region: 'Judeia',
      journey: 'Vida de Jesus',
      references: ['Lucas 24,13–35'],
    },
  },
  {
    id: 'samaria',
    name: 'Samaria',
    shortDescription: 'A região onde Jesus conversou com uma mulher junto ao poço.',
    emoji: '🪣',
    visual: { glyph: '🪣', backgroundColor: '#D6E3D3' },
    story: [
      'Ao atravessar a Samaria, Jesus parou junto a um poço e pediu água.',
      'Sua conversa com uma mulher samaritana falou de verdade, acolhimento e vida nova.',
    ],
    fact: 'A Samaria ficava entre as regiões da Judeia e da Galileia.',
    metadata: {
      period: 'Antigo e Novo Testamento',
      placeType: 'Região',
      region: 'Samaria',
      journey: 'Vida de Jesus',
      references: ['João 4,4–42'],
    },
  },
  {
    id: 'sea-of-galilee',
    name: 'Mar da Galileia',
    shortDescription: 'O grande lago onde Jesus ensinou e acalmou a tempestade.',
    emoji: '🌊',
    visual: { glyph: '🌊', backgroundColor: '#C9E5EE' },
    story: [
      'Jesus e os discípulos atravessavam o Mar da Galileia quando começou uma forte tempestade.',
      'Jesus acalmou o vento e as ondas, convidando os discípulos a confiar.',
    ],
    fact: 'Apesar do nome, o Mar da Galileia é um lago de água doce.',
    metadata: {
      period: 'Novo Testamento',
      placeType: 'Mar',
      region: 'Galileia',
      journey: 'Vida de Jesus',
      references: ['Marcos 4,35–41'],
    },
  },
  {
    id: 'jordan-river',
    name: 'Rio Jordão',
    shortDescription: 'O rio onde Jesus recebeu o Batismo de João.',
    emoji: '💧',
    visual: { glyph: '💧', backgroundColor: '#C9E8EA' },
    story: [
      'João Batista anunciava a conversão e batizava pessoas no Rio Jordão.',
      'Jesus também foi ao Jordão, e o Espírito Santo desceu sobre ele após o Batismo.',
    ],
    fact: 'No Antigo Testamento, o povo de Israel atravessou o Jordão ao entrar na Terra Prometida.',
    metadata: {
      period: 'Antigo e Novo Testamento',
      placeType: 'Rio',
      region: 'Vale do Jordão',
      journey: 'Antigo e Novo Testamento',
      references: ['Josué 3', 'Mateus 3,13–17'],
    },
  },
  {
    id: 'mount-sinai',
    name: 'Monte Sinai',
    shortDescription: 'O monte da aliança de Deus com o povo de Israel.',
    emoji: '⛰️',
    visual: { glyph: '⛰', backgroundColor: '#E8D3BB' },
    story: [
      'Depois de sair do Egito, o povo de Israel chegou ao Monte Sinai.',
      'Ali, Deus fez uma aliança com o povo e entregou os mandamentos a Moisés.',
    ],
    fact: 'O relato bíblico apresenta o Sinai como um lugar de encontro, escuta e compromisso.',
    metadata: {
      period: 'Antigo Testamento',
      placeType: 'Monte',
      region: 'Sinai',
      journey: 'Povo de Israel',
      references: ['Êxodo 19–20'],
    },
  },
  {
    id: 'mount-of-olives',
    name: 'Monte das Oliveiras',
    shortDescription: 'O monte próximo a Jerusalém onde Jesus costumava rezar.',
    emoji: '🫒',
    visual: { glyph: '🫒', backgroundColor: '#D9E3BE' },
    story: [
      'Jesus foi muitas vezes ao Monte das Oliveiras, perto de Jerusalém.',
      'Na noite antes de sua prisão, rezou ali com os discípulos.',
    ],
    fact: 'O livro dos Atos menciona o monte quando os discípulos voltam a Jerusalém após a Ascensão.',
    metadata: {
      period: 'Novo Testamento',
      placeType: 'Monte',
      region: 'Judeia',
      journey: 'Vida de Jesus',
      references: ['Lucas 22,39–46', 'Atos 1,9–12'],
    },
  },
  {
    id: 'judean-desert',
    name: 'Deserto da Judeia',
    shortDescription: 'A região desértica onde João Batista anunciava a conversão.',
    emoji: '🏜️',
    visual: { glyph: '🏜', backgroundColor: '#EACCA2' },
    story: [
      'João Batista apareceu no deserto da Judeia preparando o caminho do Senhor.',
      'Muitas pessoas iam até ele para ouvir sua mensagem e receber o batismo.',
    ],
    fact: 'Na Bíblia, o deserto pode ser lugar de silêncio, provação e encontro com Deus.',
    metadata: {
      period: 'Novo Testamento',
      placeType: 'Deserto',
      region: 'Judeia',
      journey: 'Vida de Jesus',
      references: ['Mateus 3,1–6'],
    },
  },
  {
    id: 'egypt',
    name: 'Egito',
    shortDescription: 'A terra do Êxodo e do refúgio da Sagrada Família.',
    emoji: '🌴',
    visual: { glyph: '🌴', backgroundColor: '#F0D5A4' },
    story: [
      'Deus libertou o povo de Israel da escravidão no Egito e o conduziu pelo deserto.',
      'Muitos anos depois, José levou Maria e o menino Jesus ao Egito para protegê-lo.',
    ],
    fact: 'O Egito liga acontecimentos importantes do Antigo e do Novo Testamento.',
    metadata: {
      period: 'Antigo e Novo Testamento',
      placeType: 'País',
      region: 'Egito',
      journey: 'Antigo e Novo Testamento',
      references: ['Êxodo 12–14', 'Mateus 2,13–15'],
    },
  },
  {
    id: 'damascus',
    name: 'Damasco',
    shortDescription: 'A cidade ligada ao chamado e à conversão de Saulo.',
    emoji: '✨',
    visual: { glyph: '✨', backgroundColor: '#F3E0AE' },
    story: [
      'Saulo viajava para Damasco quando uma luz o envolveu e ele ouviu a voz de Jesus.',
      'Na cidade, Ananias o acolheu, e Saulo começou uma vida nova como discípulo.',
    ],
    fact: 'Saulo ficou conhecido como Paulo e tornou-se um grande anunciador do Evangelho.',
    metadata: {
      period: 'Novo Testamento',
      placeType: 'Cidade',
      region: 'Síria',
      journey: 'Primeira Igreja',
      references: ['Atos 9,1–19'],
    },
  },
  {
    id: 'antioch',
    name: 'Antioquia',
    shortDescription: 'Uma cidade importante para as primeiras comunidades cristãs.',
    emoji: '⛪',
    visual: { glyph: '⛪', backgroundColor: '#E2D7C7' },
    story: [
      'Os discípulos anunciaram Jesus em Antioquia a pessoas de diferentes origens.',
      'Barnabé e Saulo ajudaram a ensinar e fortalecer aquela comunidade.',
    ],
    fact: 'Foi em Antioquia que os discípulos foram chamados cristãos pela primeira vez.',
    metadata: {
      period: 'Novo Testamento',
      placeType: 'Cidade',
      region: 'Síria',
      journey: 'Primeira Igreja',
      references: ['Atos 11,19–26'],
    },
  },
  {
    id: 'patmos',
    name: 'Ilha de Patmos',
    shortDescription: 'A ilha onde João recebeu as visões do Apocalipse.',
    emoji: '📜',
    visual: { glyph: '📜', backgroundColor: '#D7E5EA' },
    story: [
      'João estava na ilha de Patmos por causa da Palavra de Deus e do testemunho de Jesus.',
      'Ali, recebeu a visão que deu origem ao livro do Apocalipse.',
    ],
    fact: 'Patmos é uma pequena ilha cercada pelo Mar Egeu.',
    metadata: {
      period: 'Novo Testamento',
      placeType: 'Ilha',
      region: 'Mar Egeu',
      journey: 'Primeira Igreja',
      references: ['Apocalipse 1,9–11'],
    },
  },
];
