const SYMBOL_CONTENT = [
  {
    id: 'cross',
    name: 'Cruz',
    image: require('../../../assets/symbols/01-cross.png'),
    shortDescription: 'Recorda o amor de Jesus e sua vitória sobre a morte.',
    emoji: '✝️',
    visual: { glyph: '✝', backgroundColor: '#F3D8C7' },
    story: [
      'Jesus entregou sua vida na cruz por amor a toda a humanidade.',
      'Para os cristãos, a cruz também aponta para a Ressurreição e para a esperança.',
    ],
    fact: 'O sinal da cruz recorda o Pai, o Filho e o Espírito Santo.',
    metadata: { category: 'Jesus Cristo', context: 'Igreja e oração' },
  },
  {
    id: 'bible',
    name: 'Bíblia',
    image: require('../../../assets/symbols/02-bible.png'),
    shortDescription: 'O livro que reúne a Palavra de Deus.',
    emoji: '📖',
    visual: { glyph: '📖', backgroundColor: '#D9E8F2' },
    story: [
      'A Bíblia conta a história da aliança de Deus com seu povo.',
      'Nos Evangelhos, conhecemos de modo especial a vida e os ensinamentos de Jesus.',
    ],
    fact: 'Na Missa, as leituras bíblicas fazem parte da Liturgia da Palavra.',
    metadata: { category: 'Palavra de Deus', context: 'Bíblia e liturgia' },
  },
  {
    id: 'chalice',
    name: 'Cálice',
    image: require('../../../assets/symbols/03-calice.png'),
    shortDescription: 'Um vaso sagrado usado na celebração da Eucaristia.',
    emoji: '🏆',
    visual: { glyph: '♕', backgroundColor: '#F4E4AD' },
    story: [
      'O cálice recebe o vinho que será consagrado durante a Missa.',
      'Ele recorda a Última Ceia de Jesus com seus discípulos.',
    ],
    fact: 'Por seu uso na Eucaristia, o cálice é tratado com grande cuidado e respeito.',
    metadata: { category: 'Eucaristia', context: 'Liturgia' },
  },
  {
    id: 'host',
    name: 'Hóstia',
    image: require('../../../assets/symbols/06-ihs.png'),
    shortDescription: 'O pão preparado para a celebração da Eucaristia.',
    emoji: '☀️',
    visual: { glyph: 'IHS', backgroundColor: '#FFF3C9' },
    story: [
      'Na Missa, o pão e o vinho são consagrados e tornam-se o Corpo e o Sangue de Cristo.',
      'A Eucaristia alimenta a vida de fé e une a comunidade a Jesus.',
    ],
    fact: 'As letras IHS são um antigo monograma do nome de Jesus.',
    metadata: { category: 'Eucaristia', context: 'Liturgia' },
  },
  {
    id: 'fish',
    name: 'Peixe cristão',
    image: require('../../../assets/symbols/05-fish.png'),
    shortDescription: 'Um dos sinais usados pelos primeiros cristãos.',
    emoji: '🐟',
    visual: { glyph: '🐟', backgroundColor: '#CFE8EB' },
    story: [
      'A palavra grega para peixe ajudava os primeiros cristãos a recordar quem é Jesus.',
      'O desenho simples tornou-se um sinal de identificação e de fé.',
    ],
    fact: 'Em grego, as letras de “peixe” formam um antigo resumo da fé em Jesus Cristo.',
    metadata: { category: 'Primeiros cristãos', context: 'História da Igreja' },
  },
  {
    id: 'lamb',
    name: 'Cordeiro',
    image: require('../../../assets/symbols/04-lamb.png'),
    shortDescription: 'Recorda Jesus, chamado Cordeiro de Deus.',
    emoji: '🐑',
    visual: { glyph: '🐑', backgroundColor: '#E8E2F2' },
    story: [
      'João Batista apresentou Jesus como o Cordeiro de Deus.',
      'O cordeiro recorda a entrega, a mansidão e a vitória de Cristo.',
    ],
    fact: 'Na Missa, a comunidade reza “Cordeiro de Deus” antes da Comunhão.',
    metadata: { category: 'Jesus Cristo', context: 'Bíblia e liturgia' },
  },
  {
    id: 'dove',
    name: 'Pomba',
    image: require('../../../assets/symbols/07-dove.png'),
    shortDescription: 'Um sinal que recorda o Espírito Santo.',
    emoji: '🕊️',
    visual: { glyph: '🕊', backgroundColor: '#DCECF6' },
    story: [
      'Depois do dilúvio, uma pomba trouxe a Noé um ramo de oliveira.',
      'No Batismo de Jesus, o Espírito Santo desceu sobre ele como uma pomba.',
    ],
    fact: 'A pomba também é lembrada como sinal de paz e esperança.',
    metadata: { category: 'Espírito Santo', context: 'Bíblia e sacramentos' },
  },
  {
    id: 'rosary',
    name: 'Rosário',
    image: require('../../../assets/symbols/08-terco.png'),
    shortDescription: 'Uma oração que contempla a vida de Jesus com Maria.',
    emoji: '📿',
    visual: { glyph: '📿', backgroundColor: '#E4D9EF' },
    story: [
      'As contas ajudam a acompanhar as orações e os mistérios contemplados.',
      'Ao rezar o Rosário, recordamos momentos da vida, morte e Ressurreição de Jesus.',
    ],
    fact: 'A palavra “rosário” lembra uma coroa de rosas oferecida em oração.',
    metadata: { category: 'Maria e oração', context: 'Oração' },
  },
  {
    id: 'sacred-heart',
    name: 'Sagrado Coração',
    image: require('../../../assets/symbols/09-hearth.png'),
    shortDescription: 'Recorda o amor de Jesus por todas as pessoas.',
    emoji: '❤️',
    visual: { glyph: '❤', backgroundColor: '#F4CACA' },
    story: [
      'O coração é um sinal humano de amor, cuidado e entrega.',
      'Na devoção ao Sagrado Coração, contemplamos o amor misericordioso de Jesus.',
    ],
    fact: 'A chama costuma representar um amor vivo e ardente.',
    metadata: { category: 'Jesus Cristo', context: 'Devoção e oração' },
  },
  {
    id: 'alpha-omega',
    name: 'Alfa e Ômega',
    image: require('../../../assets/symbols/10-az.png'),
    shortDescription: 'A primeira e a última letras do alfabeto grego.',
    emoji: '🔠',
    visual: { glyph: 'Α Ω', backgroundColor: '#D9E5C6' },
    story: [
      'No livro do Apocalipse, Alfa e Ômega expressam o princípio e o fim.',
      'Juntas, as letras recordam que toda a história encontra sentido em Deus.',
    ],
    fact: 'Essas letras aparecem com frequência no Círio Pascal.',
    metadata: { category: 'Jesus Cristo', context: 'Bíblia e liturgia' },
  },
  {
    id: 'chi-rho',
    name: 'Chi-Rho',
    image: require('../../../assets/symbols/11-px.png'),
    shortDescription: 'Um antigo monograma formado com letras do nome de Cristo.',
    emoji: '☧',
    visual: { glyph: '☧', backgroundColor: '#E5D5B9' },
    story: [
      'Chi e Rho são as primeiras letras da palavra “Cristo” em grego.',
      'Os cristãos uniram essas letras para formar um sinal de Jesus.',
    ],
    fact: 'O monograma também é conhecido pelo nome de cristograma.',
    metadata: { category: 'Primeiros cristãos', context: 'História da Igreja' },
  },
  {
    id: 'anchor',
    name: 'Âncora',
    image: require('../../../assets/symbols/12-ancora.png'),
    shortDescription: 'Um sinal cristão de esperança firme em Deus.',
    emoji: '⚓',
    visual: { glyph: '⚓', backgroundColor: '#C9DEE8' },
    story: [
      'A âncora mantém um barco firme mesmo quando o mar está agitado.',
      'Por isso, os cristãos a usam para recordar a esperança que sustenta a vida.',
    ],
    fact: 'A Carta aos Hebreus compara a esperança a uma âncora segura para a alma.',
    metadata: { category: 'Virtudes', context: 'Bíblia e tradição' },
  },
  {
    id: 'keys',
    name: 'Chaves de São Pedro',
    image: require('../../../assets/symbols/15-chaves.png'),
    shortDescription: 'Recordam a missão confiada por Jesus a Pedro.',
    emoji: '🗝️',
    visual: { glyph: '🗝', backgroundColor: '#F0D9A7' },
    story: [
      'Jesus falou a Pedro sobre as chaves do Reino dos Céus.',
      'As chaves se tornaram um sinal do serviço e da missão de Pedro na Igreja.',
    ],
    fact: 'Duas chaves cruzadas aparecem no brasão da Santa Sé.',
    metadata: { category: 'Igreja', context: 'Bíblia e tradição' },
  },
  {
    id: 'lily',
    name: 'Lírio',
    image: require('../../../assets/symbols/14-flor.png'),
    shortDescription: 'Uma flor associada à pureza e à confiança em Deus.',
    emoji: '🌸',
    visual: { glyph: '⚜', backgroundColor: '#E7E8D1' },
    story: [
      'Na arte cristã, o lírio pode recordar pureza, beleza e entrega a Deus.',
      'Ele aparece em imagens de Maria e também de São José.',
    ],
    fact: 'Nas imagens de São José, o lírio ajuda a reconhecê-lo.',
    metadata: { category: 'Maria e santos', context: 'Arte e tradição' },
  },
  {
    id: 'paschal-candle',
    name: 'Círio Pascal',
    image: require('../../../assets/symbols/13-vela.png'),
    shortDescription: 'A grande vela que recorda Cristo ressuscitado.',
    emoji: '🕯️',
    visual: { glyph: '🕯', backgroundColor: '#F7E8B8' },
    story: [
      'O Círio é aceso solenemente na Vigília Pascal.',
      'Sua luz recorda que Cristo ressuscitado vence as trevas.',
    ],
    fact: 'Ele costuma trazer uma cruz, o ano e as letras Alfa e Ômega.',
    metadata: { category: 'Páscoa', context: 'Liturgia' },
  },
  {
    id: 'baptismal-water',
    name: 'Água do Batismo',
    image: require('../../../assets/symbols/16-agua.png'),
    shortDescription: 'Sinal sacramental de vida nova em Cristo.',
    emoji: '💧',
    visual: { glyph: '💧', backgroundColor: '#CBEAF2' },
    story: [
      'A água é essencial para a vida e também pode lavar e renovar.',
      'No Batismo, ela é o sinal sacramental do novo nascimento pela água e pelo Espírito.',
    ],
    fact: 'O Batismo é a porta de entrada para a vida sacramental da Igreja.',
    metadata: { category: 'Sacramentos', context: 'Batismo' },
  },
  {
    id: 'incense',
    name: 'Incenso',
    image: require('../../../assets/symbols/17-incenso.png'),
    shortDescription: 'Sua fumaça perfumada recorda a oração que sobe a Deus.',
    emoji: '💨',
    visual: { glyph: '♨', backgroundColor: '#DDD5CC' },
    story: [
      'O incenso é usado em algumas celebrações para honrar pessoas e coisas sagradas.',
      'A fumaça que sobe ajuda a recordar a oração oferecida a Deus.',
    ],
    fact: 'O recipiente usado para queimar incenso é chamado turíbulo.',
    metadata: { category: 'Oração', context: 'Liturgia' },
  },
  {
    id: 'boat',
    name: 'Barca da Igreja',
    image: require('../../../assets/symbols/18-barco.png'),
    shortDescription: 'Recorda a Igreja navegando com Cristo.',
    emoji: '⛵',
    visual: { glyph: '⛵', backgroundColor: '#C7E0E6' },
    story: [
      'Os Evangelhos contam vários encontros de Jesus com os discípulos em barcos.',
      'A barca tornou-se uma imagem da Igreja reunida e guiada por Cristo.',
    ],
    fact: 'A parte central de muitas igrejas é chamada nave, palavra ligada à ideia de navio.',
    metadata: { category: 'Igreja', context: 'Bíblia e tradição' },
  },
];

// Symbol illustrations already contain the complete visual, so the emoji
// badge used over saint portraits would be redundant here. Keep the glyphs as
// a graceful fallback if an image is temporarily removed.
export const SYMBOL_ITEMS = SYMBOL_CONTENT.map((item) => ({
  ...item,
  showEmojiBadge: false,
}));
