// Conteúdo introdutório para crianças e famílias. As referências ajudam na
// revisão editorial; o texto deve passar por revisão bíblica e catequética
// antes de uma publicação definitiva.
export const PARABLE_ITEMS = [
  {
    id: 'good-samaritan',
    image: require('../../../assets/parables/01-good-samaritan.png'),
    showEmojiBadge: false,
    name: 'O Bom Samaritano',
    shortDescription: 'Um viajante escolhe cuidar de quem precisava.',
    emoji: '🤝',
    visual: { glyph: '🤝', backgroundColor: '#F2D2B6' },
    story: [
      'Jesus contou sobre um homem ferido que foi encontrado no caminho.',
      'Um samaritano se aproximou, cuidou dele e garantiu que estivesse seguro.',
      'Jesus nos ensina a ser próximos de toda pessoa que precisa de ajuda.',
    ],
    fact: 'O amor ao próximo aparece em atitudes concretas de cuidado e misericórdia.',
    metadata: {
      gospel: 'Lucas',
      teaching: 'Misericórdia',
      mainElement: 'Pessoa',
      references: ['Lucas 10,25–37'],
    },
  },
  {
    id: 'merciful-father',
    image: require('../../../assets/parables/02-merciful-father.png'),
    showEmojiBadge: false,
    name: 'O Pai Misericordioso',
    shortDescription: 'Um pai acolhe com alegria o filho que voltou.',
    emoji: '🫂',
    visual: { glyph: '🫂', backgroundColor: '#EDC9B9' },
    story: [
      'Um filho saiu de casa e gastou tudo o que havia recebido.',
      'Quando decidiu voltar, seu pai correu para abraçá-lo e preparou uma festa.',
      'Jesus revela a alegria de Deus quando alguém aceita seu amor e recomeça.',
    ],
    fact: 'Esta história também é conhecida como a parábola do Filho Pródigo.',
    metadata: {
      gospel: 'Lucas',
      teaching: 'Misericórdia',
      mainElement: 'Pessoa',
      references: ['Lucas 15,11–32'],
    },
  },
  {
    id: 'sower',
    image: require('../../../assets/parables/03-sower.png'),
    showEmojiBadge: false,
    name: 'O Semeador',
    shortDescription: 'Sementes caem em solos diferentes e produzem frutos.',
    emoji: '🌾',
    visual: { glyph: '🌾', backgroundColor: '#E6D5A5' },
    story: [
      'Um semeador espalhou sementes pelo caminho, entre pedras, entre espinhos e em terra boa.',
      'As sementes da terra boa cresceram e deram muitos frutos.',
      'Jesus nos convida a acolher a Palavra e deixá-la transformar nossa vida.',
    ],
    fact: 'A mesma semente encontra resultados diferentes conforme o solo que a recebe.',
    metadata: {
      gospel: 'Mateus',
      teaching: 'Palavra em prática',
      mainElement: 'Natureza',
      references: ['Mateus 13,1–23'],
    },
  },
  {
    id: 'lost-sheep',
    image: require('../../../assets/parables/04-lost-sheep.png'),
    showEmojiBadge: false,
    name: 'A Ovelha Perdida',
    shortDescription: 'O pastor procura com cuidado uma ovelha perdida.',
    emoji: '🐑',
    visual: { glyph: '🐑', backgroundColor: '#DDE6CF' },
    story: [
      'Um pastor percebeu que uma de suas cem ovelhas havia se perdido.',
      'Ele foi procurá-la e voltou cheio de alegria quando a encontrou.',
      'Jesus mostra que cada pessoa é importante para Deus.',
    ],
    fact: 'A alegria do pastor ajuda a compreender a misericórdia de Deus.',
    metadata: {
      gospel: 'Lucas',
      teaching: 'Misericórdia',
      mainElement: 'Animal',
      references: ['Lucas 15,1–7'],
    },
  },
  {
    id: 'lost-coin',
    image: require('../../../assets/parables/05-lost-coin.png'),
    showEmojiBadge: false,
    name: 'A Moeda Perdida',
    shortDescription: 'Uma mulher procura até encontrar sua moeda.',
    emoji: '🪙',
    visual: { glyph: '🪙', backgroundColor: '#F5E1A7' },
    story: [
      'Uma mulher perdeu uma de suas dez moedas dentro de casa.',
      'Ela acendeu uma lamparina, varreu tudo e procurou até encontrar.',
      'Ao achar a moeda, chamou as amigas para partilhar sua alegria.',
    ],
    fact: 'Jesus compara essa alegria à alegria de Deus por quem escolhe voltar para ele.',
    metadata: {
      gospel: 'Lucas',
      teaching: 'Misericórdia',
      mainElement: 'Objeto',
      references: ['Lucas 15,8–10'],
    },
  },
  {
    id: 'mustard-seed',
    image: require('../../../assets/parables/06-mustard-seed.png'),
    showEmojiBadge: false,
    name: 'O Grão de Mostarda',
    shortDescription: 'Uma semente muito pequena cresce e oferece abrigo.',
    emoji: '🌱',
    visual: { glyph: '🌱', backgroundColor: '#D9E7BA' },
    story: [
      'Jesus comparou o Reino dos Céus a um pequeno grão de mostarda.',
      'Depois de plantado, ele cresce e se torna um grande arbusto.',
      'O Reino pode começar discretamente e produzir algo muito maior.',
    ],
    fact: 'Pequenas atitudes de fé e amor também podem crescer e dar muitos frutos.',
    metadata: {
      gospel: 'Mateus',
      teaching: 'Reino de Deus',
      mainElement: 'Natureza',
      references: ['Mateus 13,31–32'],
    },
  },
  {
    id: 'leaven',
    image: require('../../../assets/parables/07-leaven.png'),
    showEmojiBadge: false,
    name: 'O Fermento na Massa',
    shortDescription: 'Um pouco de fermento transforma toda a massa.',
    emoji: '🍞',
    visual: { glyph: '🍞', backgroundColor: '#EBD1A8' },
    story: [
      'Jesus comparou o Reino dos Céus ao fermento misturado à farinha.',
      'Mesmo quase escondido, ele faz toda a massa crescer.',
      'A presença do Reino transforma a vida por dentro.',
    ],
    fact: 'Uma pequena quantidade de fermento pode alcançar toda a massa.',
    metadata: {
      gospel: 'Mateus',
      teaching: 'Reino de Deus',
      mainElement: 'Alimento',
      references: ['Mateus 13,33'],
    },
  },
  {
    id: 'hidden-treasure',
    image: require('../../../assets/parables/08-hidden-treasure.png'),
    showEmojiBadge: false,
    name: 'O Tesouro Escondido',
    shortDescription: 'Um tesouro encontrado enche de alegria quem o descobre.',
    emoji: '💎',
    visual: { glyph: '💎', backgroundColor: '#D6E6E5' },
    story: [
      'Jesus falou de um homem que encontrou um tesouro escondido no campo.',
      'Cheio de alegria, ele decidiu fazer o necessário para ficar com aquele campo.',
      'A parábola mostra o valor incomparável do Reino de Deus.',
    ],
    fact: 'A decisão do homem nasce da alegria de ter descoberto algo precioso.',
    metadata: {
      gospel: 'Mateus',
      teaching: 'Reino de Deus',
      mainElement: 'Objeto',
      references: ['Mateus 13,44'],
    },
  },
  {
    id: 'precious-pearl',
    image: require('../../../assets/parables/09-precious-pearl.png'),
    showEmojiBadge: false,
    name: 'A Pérola Preciosa',
    shortDescription: 'Um comerciante reconhece uma pérola de grande valor.',
    emoji: '🦪',
    visual: { glyph: '◉', backgroundColor: '#E4DDF0' },
    story: [
      'Um comerciante procurava pérolas de grande valor.',
      'Quando encontrou uma pérola extraordinária, escolheu ficar com ela.',
      'Jesus nos convida a reconhecer o Reino como um bem precioso.',
    ],
    fact: 'Encontrar o que realmente importa também ajuda a escolher como viver.',
    metadata: {
      gospel: 'Mateus',
      teaching: 'Reino de Deus',
      mainElement: 'Objeto',
      references: ['Mateus 13,45–46'],
    },
  },
  {
    id: 'house-on-rock',
    image: require('../../../assets/parables/10-house-on-rock.png'),
    showEmojiBadge: false,
    name: 'A Casa sobre a Rocha',
    shortDescription: 'Uma casa firme resiste à chuva e ao vento.',
    emoji: '🏠',
    visual: { glyph: '🏠', backgroundColor: '#D5DEE8' },
    story: [
      'Jesus contou sobre duas casas: uma construída sobre a rocha e outra sobre a areia.',
      'Quando vieram a chuva e o vento, somente a casa com base firme permaneceu.',
      'Ouvir Jesus e praticar sua Palavra dá fundamento à nossa vida.',
    ],
    fact: 'A parábola aparece no final do Sermão da Montanha.',
    metadata: {
      gospel: 'Mateus',
      teaching: 'Palavra em prática',
      mainElement: 'Objeto',
      references: ['Mateus 7,24–27'],
    },
  },
  {
    id: 'talents',
    image: require('../../../assets/parables/11-talents.png'),
    showEmojiBadge: false,
    name: 'Os Talentos',
    shortDescription: 'Servos recebem bens para cuidar com responsabilidade.',
    emoji: '🪙',
    visual: { glyph: '🪙🪙', backgroundColor: '#E8D2A1' },
    story: [
      'Antes de viajar, um homem confiou diferentes quantias a seus servos.',
      'Ao voltar, perguntou como cada um havia cuidado do que recebeu.',
      'Jesus nos chama a usar com responsabilidade os bens e dons confiados a nós.',
    ],
    fact: 'Na parábola, “talento” era uma grande medida de dinheiro.',
    metadata: {
      gospel: 'Mateus',
      teaching: 'Responsabilidade',
      mainElement: 'Objeto',
      references: ['Mateus 25,14–30'],
    },
  },
  {
    id: 'ten-virgins',
    image: require('../../../assets/parables/12-ten-virgins.png'),
    showEmojiBadge: false,
    name: 'As Dez Jovens',
    shortDescription: 'Jovens aguardam uma festa com suas lamparinas.',
    emoji: '🪔',
    visual: { glyph: '🪔', backgroundColor: '#F3D9A6' },
    story: [
      'Dez jovens saíram com suas lamparinas para esperar o início de uma festa de casamento.',
      'Algumas levaram azeite suficiente e estavam preparadas para a espera.',
      'Jesus ensina a viver com atenção e o coração pronto para Deus.',
    ],
    fact: 'A lamparina acesa tornou-se uma imagem de vigilância e preparação.',
    metadata: {
      gospel: 'Mateus',
      teaching: 'Vigilância',
      mainElement: 'Objeto',
      references: ['Mateus 25,1–13'],
    },
  },
  {
    id: 'pharisee-tax-collector',
    image: require('../../../assets/parables/13-pharisee-tax-collector.png'),
    showEmojiBadge: false,
    name: 'O Fariseu e o Cobrador de Impostos',
    shortDescription: 'Duas pessoas rezam com atitudes muito diferentes.',
    emoji: '🙏',
    visual: { glyph: '🙏', backgroundColor: '#DDD8EA' },
    story: [
      'Jesus contou sobre duas pessoas que foram ao templo para rezar.',
      'Uma se considerava melhor que as outras; a outra reconheceu com humildade que precisava de Deus.',
      'A verdadeira oração não despreza ninguém e abre o coração à misericórdia.',
    ],
    fact: 'Jesus dirigiu esta parábola a quem confiava apenas na própria justiça.',
    metadata: {
      gospel: 'Lucas',
      teaching: 'Oração e humildade',
      mainElement: 'Pessoa',
      references: ['Lucas 18,9–14'],
    },
  },
  {
    id: 'rich-fool',
    image: require('../../../assets/parables/14-rich-fool.png'),
    showEmojiBadge: false,
    name: 'O Rico Insensato',
    shortDescription: 'Celeiros cheios não garantem o sentido da vida.',
    emoji: '🏚️',
    visual: { glyph: '🌾🏚', backgroundColor: '#DFCEAA' },
    story: [
      'Um homem teve uma colheita tão grande que decidiu construir celeiros maiores.',
      'Ele pensou somente em acumular bens e esqueceu que a vida é um presente de Deus.',
      'Jesus nos lembra que a riqueza verdadeira não está em guardar tudo para si.',
    ],
    fact: 'A parábola nasceu de uma pergunta dirigida a Jesus sobre uma herança.',
    metadata: {
      gospel: 'Lucas',
      teaching: 'Responsabilidade',
      mainElement: 'Alimento',
      references: ['Lucas 12,13–21'],
    },
  },
  {
    id: 'watchful-servants',
    image: require('../../../assets/parables/15-watchful-servants.png'),
    showEmojiBadge: false,
    name: 'Os Servos Vigilantes',
    shortDescription: 'Servos mantêm as luzes acesas enquanto esperam.',
    emoji: '🕯️',
    visual: { glyph: '🕯', backgroundColor: '#F4E2B0' },
    story: [
      'Jesus falou de servos que aguardavam o retorno de seu senhor.',
      'Eles mantinham as lâmpadas acesas e estavam prontos para abrir a porta.',
      'A vigilância cristã é viver cada dia com fidelidade e disposição para o bem.',
    ],
    fact: 'Estar preparado significa cuidar bem das responsabilidades de cada dia.',
    metadata: {
      gospel: 'Lucas',
      teaching: 'Vigilância',
      mainElement: 'Pessoa',
      references: ['Lucas 12,35–48'],
    },
  },
  {
    id: 'great-banquet',
    image: require('../../../assets/parables/16-great-banquet.png'),
    showEmojiBadge: false,
    name: 'O Grande Banquete',
    shortDescription: 'Uma grande mesa está preparada e o convite se amplia.',
    emoji: '🍽️',
    visual: { glyph: '🍽', backgroundColor: '#EDD0C2' },
    story: [
      'Um homem preparou uma grande festa e enviou convites aos convidados.',
      'Quando muitos recusaram, ele mandou chamar outras pessoas pelas ruas e caminhos.',
      'Jesus apresenta o convite generoso de Deus e nos chama a acolhê-lo.',
    ],
    fact: 'A imagem do banquete fala de comunhão, alegria e acolhida.',
    metadata: {
      gospel: 'Lucas',
      teaching: 'Reino de Deus',
      mainElement: 'Alimento',
      references: ['Lucas 14,15–24'],
    },
  },
  {
    id: 'wheat-weeds',
    image: require('../../../assets/parables/17-wheat-weeds.png'),
    showEmojiBadge: false,
    name: 'O Trigo e o Joio',
    shortDescription: 'Trigo e ervas crescem juntos até a colheita.',
    emoji: '🌾',
    visual: { glyph: '🌾🌿', backgroundColor: '#DCE1B5' },
    story: [
      'Um homem semeou boa semente, mas depois apareceram ervas no meio do trigo.',
      'O dono do campo pediu paciência para não arrancar o trigo junto com elas.',
      'Jesus ensina a confiar na justiça de Deus e a não julgar apressadamente.',
    ],
    fact: 'A paciência do dono do campo protege aquilo que ainda está crescendo.',
    metadata: {
      gospel: 'Mateus',
      teaching: 'Vigilância',
      mainElement: 'Natureza',
      references: ['Mateus 13,24–30', 'Mateus 13,36–43'],
    },
  },
  {
    id: 'fishing-net',
    image: require('../../../assets/parables/18-fishing-net.png'),
    showEmojiBadge: false,
    name: 'A Rede Lançada ao Mar',
    shortDescription: 'Uma rede reúne muitos tipos de peixe.',
    emoji: '🐟',
    visual: { glyph: '🐟', backgroundColor: '#C9E5EA' },
    story: [
      'Jesus comparou o Reino dos Céus a uma rede lançada ao mar.',
      'Quando ficou cheia, os pescadores a puxaram para a praia e organizaram os peixes.',
      'A parábola convida a acolher o Reino e fazer escolhas que conduzem ao bem.',
    ],
    fact: 'A pesca era uma imagem familiar para muitas pessoas que ouviam Jesus na Galileia.',
    metadata: {
      gospel: 'Mateus',
      teaching: 'Reino de Deus',
      mainElement: 'Animal',
      references: ['Mateus 13,47–50'],
    },
  },
];
